dist: xenial
sudo: required
language: go
go: "1.12.x"

services:
  - redis

env:
  global:
    - REDIS_ADDR=127.0.0.1
    # REDIS_PASS
    - secure: "mfsRG0d0xMGkG2K4uxe5pDwCDp/o6lM1I3bP3bw7cFYG+6yi0gUKPJZW0X1WNi9o+tj8m5+ahHd/qoGZbJBSMGx/t1zkQId1XB7BRM1KYbkv4NeQCYU6Zx6bha1qU+pqHYwvrNdML07CyuMyk+Bo04osSAuDBY+pH8h5P21f3dAzAGgd1ZPlFkUUVzow90G6EPUyCFlBmqlKGTmpOhS1m9vtREulsBWLg5rgx6btchThXXYZCiFlnZNa8YcKTcV/hViV9DHKi9kPGUfYtD4YGxHOhb6X0ysgNKEym29LKsPL9FugUaNvqWttr5OAtbEI/Wj0oE2NWm0QAdGu8pqJh0J3fuKIAxxLYfAD6H+4W8nvHRW2kvYT01co3fVSXmju9G3gByPl95IvvByERRVYk63tF1z+Ig1RkEsTtH2Z7Fjj9PEYvUBqHMNs67pl7ThAXBTs5KlylbB3e404bGYbSX2Uw8FrkmC/EGoji2me3MMtq/BN8CrMUCkQduSdLXamJVNHru7jsYH/f3VbFYA7UJnAFJXKRosGWWH07PU9STDuOsnCPlsRNJKnpUHRd0ZR4BaoiRSnjhwUHI8yN/3y5TwjiJcdQqHr8060VCaPfjtsr/FvuPlcJbYdlE5gsf3NLZyU56neIEP4lKuJjShShhNcRwYVnFzpdMaOuFObMmc="
    - VAULT_ADDR=http://127.0.0.1:8200
    # VAULT_TOKEN
    - secure: "sOaTJdOmPqzSMK6EOwYiT/HaJNo3ZxmdHlPpMwNNOEUgcIvxRcQNUL7AzNxSbQEL3XDHMbQlJYN1uvFxS3Rp8nViOVskrJssZSyPNa+8j9TZJ9mqThOr21o2IAPB2Y+MZTKiF0GXKuJxo+yhgFmtkLxRzbpgcvAmDsNkweTXP90c5NcP3SpGP0tTy3ZZ8w28+pAIX96mkiTiga7HB1NB+IlIqvCXaO/oyf/JtAz+5kDuzlw7J2hwfNz0ifytfoyNNRuEnUE1mEdtlcHXKN9KDElP4MvaRoa1W/0mFbDPsSqERq8azZcHx74VFBoNpeGRzs7iAx3DjCnHXKz0ZrECIYmnmwRB4y4ZkL9jrh+d4V210zqC41if0pQYxEX5/m4t28tZH+KkPuAiY1soTRoxSqw2St5EOaIOs2FOjlXuHB4EdWM4IDWzM/SECFFFY+WHkxZMLNhIbVdQF2l6Jwjx1PtSMsx7VsiNFC3qfBrhg3+7G9DLqAVSZeVFBMFDzQAOEF5iTMiO1nB4fpaOb8jOE4GrG5TGOjxNiGrBEQFUZ4dGDKWZ6r0Dc3mo9m8xIsYou6N6H5maGgxQ8fO3hHzPI0BugmF7vx+EfgTfOgdKm3lL8YdPYssKb2zl3btciuQy+ubrLmaniA7MpUW50uAIpXwI0IF5oHLMtarO4Kacd6s="

before_script:
  - ruby -e 'require "erb"; redis_pass=ENV["REDIS_PASS"]; File.write("ops/config/redis.conf",ERB.new(File.read("ops/config/redis.conf.erb")).result(binding))'
  - sudo cp ops/config/redis.conf /etc/redis/redis.conf && sudo systemctl restart redis-server.service
  - ops/scripts/provision_vault.sh
  - ops/scripts/vault_setup_basic.sh $VAULT_TOKEN
  - ops/scripts/vault_add_kv_secret.sh kv/redispassword pass $REDIS_PASS
  - mkdir -p artifacts
  - pushd console; go build -o ../artifacts/console; popd
  - pushd webcounter; go build -o ../artifacts/webcounter/webcounter; cp -r html/ ../artifacts/webcounter/html; popd
  - pushd artifacts/webcounter; ./webcounter & sleep 1; popd


script:
  - go test -v -d
  - go test -v ./console/
  - go test -v ./webcounter/ -d
  - tests/test_rc_console.sh artifacts/console "$REDIS_ADDR" "$REDIS_PASS"
  - tests/test_rc_webcounter.sh

before_deploy:
- pushd artifacts/; zip -r9 webcounter.zip webcounter/; popd

deploy:
  provider: releases
  on:
    repo: slavrd/go-redis-counter
    tags: true
  file: artifacts/webcounter.zip
  skip_cleanup: true
  api_key:
    secure: "Re1edu9ADJurpKH77Bbr7AFxazE8CN3VoTaH7KEWSwCHlEmVTV0v0hvS1r/W0B8l6XvHolTCTV8cXjmWMJ6nIqSqNWEN9Swbb800Zs+1Ah1t/yTe1KM1KZZBzWeX5Ol1PMoxI9ECAP4chDH8C5QdrpULc7sLzRkKkC6gjeelKrcYK1qjH9wMXzgGUYAG9/Jrea+GjAogaco5teGEK4AqRqE2FRAdGeBAvIYQRJWF+GPb0Ty1d5HY4ZdW2SUAvvmm+x9DnOQrCRWBhJQ1vyiq9jxEJRS6iJBFSQsccNJopkTQ7WGCNyvbmssqcKPyCTiar3hnx/qYfBl0fUSRnVCb+UHu/0rerOYnCOapyJ37jBIWr08ql8RgLRc7MttDAOUgsxv4/MaNrRaNAGo8Y3Oc25mpDHi6zySggAJMMd2S42Qv1jag+GDQV3pI+TNhjWCMy2I6dwls6sYloVBf6RAzWQkyZkqTpacyK5NhNGN67tY1H0Y8fi1FYBQjYXQBLEGyalDLrc8dc7z/G+WXZkX6fiBu/kxOofcIbwTKvc14AuxKjDEdef4Zd+OY/De33bA9isN3/Tk0QyKZ0s0VQprkG6kOYoNM+q7M5s2zZVR9V+P/P+VAsr/EmHCsVVw88sHWhoKO5qz/aKHd7B/UoqClCFGH1ffGySTM3wcgpyP+wMk="
