dist: xenial
sudo: required
language: go
go: "1.12.x"

services:
  - redis

env:
  global:
    - REDIS_ADDR=localhost:6379 # must include the port as well
    # REDIS_PASS
    - secure: "mfsRG0d0xMGkG2K4uxe5pDwCDp/o6lM1I3bP3bw7cFYG+6yi0gUKPJZW0X1WNi9o+tj8m5+ahHd/qoGZbJBSMGx/t1zkQId1XB7BRM1KYbkv4NeQCYU6Zx6bha1qU+pqHYwvrNdML07CyuMyk+Bo04osSAuDBY+pH8h5P21f3dAzAGgd1ZPlFkUUVzow90G6EPUyCFlBmqlKGTmpOhS1m9vtREulsBWLg5rgx6btchThXXYZCiFlnZNa8YcKTcV/hViV9DHKi9kPGUfYtD4YGxHOhb6X0ysgNKEym29LKsPL9FugUaNvqWttr5OAtbEI/Wj0oE2NWm0QAdGu8pqJh0J3fuKIAxxLYfAD6H+4W8nvHRW2kvYT01co3fVSXmju9G3gByPl95IvvByERRVYk63tF1z+Ig1RkEsTtH2Z7Fjj9PEYvUBqHMNs67pl7ThAXBTs5KlylbB3e404bGYbSX2Uw8FrkmC/EGoji2me3MMtq/BN8CrMUCkQduSdLXamJVNHru7jsYH/f3VbFYA7UJnAFJXKRosGWWH07PU9STDuOsnCPlsRNJKnpUHRd0ZR4BaoiRSnjhwUHI8yN/3y5TwjiJcdQqHr8060VCaPfjtsr/FvuPlcJbYdlE5gsf3NLZyU56neIEP4lKuJjShShhNcRwYVnFzpdMaOuFObMmc="

before_script:
  - ruby -e 'require "erb"; redis_pass=ENV["REDIS_PASS"]; File.write("ops/config/redis.conf",ERB.new(File.read("ops/config/redis.conf.erb")).result(binding))'
  - sudo cp ops/config/redis.conf /etc/redis/redis.conf && sudo systemctl restart redis-server.service
  - mkdir -p artefacts; pushd console; go build -o ../artefacts/console; popd

script:
  - go test -v
  - tests/test_rc_console.sh artefacts/console "$REDIS_ADDR" "$REDIS_PASS"
